### ISSUE TITLE
Feature: Edit/Delete

### ISSUE THREAD

**Issue by jeremyrempel** [alexstyl/Memento-Calendar#184]
Feature: Currently no option to edit or delete events. Should have ability to edit/delete

**Comment by alexstyl** [comment]
The only way you can do that currently is pressing the '+' Floating button on the main screen. You then have to enter the name of the contact you care about, edit the events and hit SAVE. 

Have you tried that?

**Comment by jeremyrempel** [comment]
Edit works, but not intuitive. I think delete should be feature especially after facebook import. If you think this is good feature, I can probably submit as a PR.

**Comment by alexstyl** [comment]
I don't think Facebook contacts should be able to be deleted but rather
hidden. That is already implemented (if you look at the person activity
there are hints of hidding) but the UI is not there yet as I haven't
designed it.

I do agree with you though. On develop the person activity shows the events
of a contact and I would like to have an edit button and delete button for
extra modifications. We could coordinate a bit to sort this out if you are
up for it cause this days it's near impossible for me to do any proper work
on memento

**Comment by jeremyrempel** [comment]
I like the app. Hopefully can help a bit if/when time allows. 

Soft delete/hide works. Should be hidden from all views and not notify. What happens if user fat fingers the delete for wrong person and want to undo? Redo FB import to reset all records?

What are your thoughts on GUI for delete/edit? The android contacts app has edit as fab button on bottom right and delete as menu option.

**Comment by alexstyl** [comment]
Edit and Delete should only be available for contacts that are stored in
the user's device (See the Contact.kt class. The contactSource should be
SOURCE_DEVICE).
Hide and Show should be available to all contacts. A hidden contact should
not appear on the UpcomingEventsFragment or any notifications or widget.
That should already be implemented as the database right now holds the
visibility in the the
https://github.com/alexstyl/Memento-Calendar/blob/develop/android_common/src/main/java/com/alexstyl/specialdates/events/database/EventColumns.java#L22
class

Now what I haven't concluded yet is how the user can see hidden contacts
from. Maybe there could be an option from the PeopleFragment to show only
the hidden ones so that you can unhide them should there be a mistake or
you change your mind.

**Comment by alexstyl** [comment]
Out of curiosity, would something like that be enough info? I could make quick wireframes to visualise how everything is linked if that helps, but do let me know if anything is needed.

**Comment by alexstyl** [comment]
Closing out of inactivity
