### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by olayhemy** [alexstyl/Memento-Calendar#204]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions for users self-service. Would love to hear from you, thanks.

**Comment by alexstyl** [comment]
Hi @olayhemy. That would be something much much needed. 
I was planning of building an FAQ. It would be great if we had some sort of web portal for that that can be updated independently from the app's source code. As an MVP it could be just an page on the github's project, and the app would link to it using a webview/Chrome Custom Tabs. A more advanced version of that would be a webpage hosted on Firebase that would be served instead of the Github Wikipage.

What do you have in mind?

**Comment by olayhemy** [comment]
Thanks for the response and sorry for the last reply! I'm presently working on it, I will make a PR as soon as I'm done for you to merge

**Comment by alexstyl** [comment]
Closing this as it's been too old
